version: 2
updates: 
  - package-ecosystem: "npm"
    directory: "/"
    schedule: 
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: ".github/actions/local-action"
    schedule: 
      interval: "weekly"
    open-pull-requests-limit: 0
